### PR TITLE
Temporary: Do not merge

### PR DESCRIPTION
**Pull request by pshirali**
This is a PR to test deepsource's config

### CODE REVIEW

**Comment by ksindi** [comment]
Thanks @pshirali! Just ping me when ready. Really appreciate the clean up.

**Comment by pshirali** [comment]
@ksindi There's something fishy going on with Deepsource analysis, if you look at the history [here](https://deepsource.io/gh/ksindi/implements/history/runs). I've actually not made any fixes to what Deepsource used to complain about in the past PRs. This PR is _magically_ showing no issues. Not sure if new versions of Deepsource are being deployed behind the scenes, which are causing different results at different points in time.

1. I tried changing glob patterns to first exclude `tests.py`, and then included it back. No change to tests.
2. I added blank lines to `implements.py` and `tests.py` just to see if it'll force trigger a scan. Nothing happened.

Issues found with `implements.py`, `tests.py`, and `docs/conf.py` which were flagged earlier, didn't get flagged in recent runs. However, `setup.py` did get flagged, so, the analyzer is active. Not sure how/why it is being selective.

Have you seen inconsistencies in the past?

**Comment by ksindi** [comment]
I recently added it. I'm happy to remove it if we find it to be noisy.

**Comment by pshirali** [comment]
IMO, let us leave it as is. I see value in fixing some of the things which Deepsource flagged in previous runs, and excluding a few others which are intentional. It is likely that, with the current inconsistency, it may not verify my changes (or may throw something new). But hopefully over subsequent PRs we may see some improvement in what it reports. If it continues to be too noisy in the future after the cleanup, then we could take some action.

**Comment by ksindi** [comment]
Sounds good. Let me know when this is ready. I can release as a new minor version.

**Comment by pshirali** [comment]
This was a temporary branch which I was using to test deepsource's behavior. I'll decline this in a bit. I've raised another PR #15 which has all fixes. (Waiting for CI to finish. Deepsource is simply refusing to run!).

**Pull request closed without merging**
